'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Inline_QueryTesting

    '''<summary>
    '''lgInvOrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lgInvOrg As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''updPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updPanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lvInventoryOrgs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvInventoryOrgs As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''lgExecuteReader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lgExecuteReader As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtOrderNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrderNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnGetPO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGetPO As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblPONumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPONumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lgNonQuery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lgNonQuery As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''updPnlLocalOrderInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updPnlLocalOrderInfo As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lvLocalOrderInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvLocalOrderInfo As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''txtOrderNoToDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrderNoToDelete As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnDeleteOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteOrder As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblDeleteStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeleteStatus As Global.System.Web.UI.WebControls.Label
End Class
