'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Templates
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ExcelExporter.Templates", GetType(Templates).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;Cell ss:StyleID=&quot;$Style$&quot;&gt;&lt;Data ss:Type=&quot;$Type$&quot;&gt;.
        '''</summary>
        Friend Shared ReadOnly Property CellHead() As String
            Get
                Return ResourceManager.GetString("CellHead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;/Data&gt;&lt;/Cell&gt;.
        '''</summary>
        Friend Shared ReadOnly Property CellTail() As String
            Get
                Return ResourceManager.GetString("CellTail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;?mso-application progid=&quot;Excel.Sheet&quot;?&gt;
        '''&lt;Workbook xmlns=&quot;urn:schemas-microsoft-com:office:spreadsheet&quot;
        ''' xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;
        ''' xmlns:x=&quot;urn:schemas-microsoft-com:office:excel&quot;
        ''' xmlns:ss=&quot;urn:schemas-microsoft-com:office:spreadsheet&quot;
        ''' xmlns:html=&quot;http://www.w3.org/TR/REC-html40&quot;&gt;
        ''' &lt;DocumentProperties xmlns=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;
        '''  &lt;LastAuthor&gt;AALIAN&lt;/LastAuthor&gt;
        '''  &lt;Created&gt;1996-10-14T23:33:28Z&lt;/Created&gt;
        '''  &lt;LastSaved&gt;2011-03-25T2 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Head() As String
            Get
                Return ResourceManager.GetString("Head", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;Worksheet ss:Name=&quot;$SheetName$&quot;&gt;
        '''  &lt;Table ss:ExpandedColumnCount=&quot;$ColCount$&quot; ss:ExpandedRowCount=&quot;$RowCount$&quot; x:FullColumns=&quot;1&quot;.
        '''</summary>
        Friend Shared ReadOnly Property SheetHead() As String
            Get
                Return ResourceManager.GetString("SheetHead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;/Table&gt;
        '''  &lt;WorksheetOptions xmlns=&quot;urn:schemas-microsoft-com:office:excel&quot;&gt;
        '''   &lt;Selected/&gt;
        '''   &lt;ProtectObjects&gt;False&lt;/ProtectObjects&gt;
        '''   &lt;ProtectScenarios&gt;False&lt;/ProtectScenarios&gt;
        '''  &lt;/WorksheetOptions&gt;
        ''' &lt;/Worksheet&gt;.
        '''</summary>
        Friend Shared ReadOnly Property SheetTail() As String
            Get
                Return ResourceManager.GetString("SheetTail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;/Workbook&gt;.
        '''</summary>
        Friend Shared ReadOnly Property Tail() As String
            Get
                Return ResourceManager.GetString("Tail", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
